# Generated by Django 5.2.6 on 2025-10-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPersist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietTitle', models.CharField(max_length=20)),
                ('dietDescription', models.TextField(null=True)),
                ('dietData', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDia', models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=20)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='diet.dietpersist')),
            ],
        ),
    ]
