# Generated by Django 5.2.6 on 2025-10-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietpersist')),
            ],
        ),
    ]
