# Generated by Django 5.2.6 on 2025-10-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_dietpersist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietpersist',
            name='dietTitle',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='dietpersist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL),
        ),
    ]
